# Generated by Django 6.0.7 on 2026-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_current_daily_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_use_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='progress',
            field=models.CharField(choices=[('registered', 'Just registered'), ('questionnaire1', 'Questionnaire 1 done'), ('pretest', 'Pretest done'), ('training1', 'First training done'), ('posttest1', 'Post-test 1 done'), ('questionnaire2', 'Questionnaire 2 done'), ('instruction', 'Instruction page seen'), ('free_use', 'Free use period'), ('posttest2', 'Post-test 2 done'), ('questionnaire3', 'Questionnaire 3 done'), ('finished', 'Study finished')], default='registered', max_length=20),
        ),
    ]
