# Generated by Django 6.0.7 on 2026-07-29 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_free_use_started_profile_last_login_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.CharField(choices=[('q1', 'Questionnaire 1 (Background)'), ('q2', 'Questionnaire 2'), ('q3', 'Questionnaire 3')], max_length=5)),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['questionnaire'],
                'unique_together': {('user', 'questionnaire')},
            },
        ),
    ]
