# Generated by Django 6.0.7 on 2026-07-23 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RPMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='matrices/')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('correct_answer', models.CharField(max_length=10)),
                ('explanation', models.TextField(blank=True)),
                ('set_number', models.IntegerField(help_text='For fixed levels')),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('pretest', 'Pretest'), ('training', 'Training'), ('posttest', 'Posttest')], max_length=20)),
                ('condition', models.CharField(choices=[('gamified', 'Gamified'), ('control', 'Control')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('total_time_seconds', models.IntegerField(blank=True, null=True)),
                ('responses', models.JSONField(default=dict)),
                ('items', models.ManyToManyField(to='tests.rpmitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
