# Generated by Django 6.0.7 on 2026-07-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPMChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='matrices/choices/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests.rpmitem')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('item', 'index')},
            },
        ),
    ]
