# Generated by Django 6.0.7 on 2026-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rpmchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
