# Generated by Django 6.0.7 on 2026-07-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testsession_longest_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='answered_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
