# Generated by Django 6.0.7 on 2026-07-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testsession_answered_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmitem',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
